@startuml
'https://plantuml.com/class-diagram

Main *-- User
Main : + static void main()

User *-- Account
User : - String nameOfUser
User : - int ageOfUser
User : - favoriteGenres


User : + getNameOfUser()
User : + getAgeOfUser()
User : + getFavoriteGenres()
User : + Scanner getUserInput(System.in)




Account : - String userName
Account : - String password
Account : - Arraylist <User> users


Account : + Account(String userName, String password)
Account : + Scanner getUserInput(System.in)
Account : + getName()
Account : + setName()
Account : + getPassword()
Account : + setPassword()
Account : + addUsers()
Account : + addFavorite()



Account *-- MainMenu
MainMenu : + displayOptions()




MainMenu *-- Media

Enum listOfMedia
listOfMedia : 100BestMovies.txt
listOfMedia : 100BestSeries.txt


Media *-- Amedia
Interface Media
Media : + getName()
Media : + getYearOfRelease()
Media : + getGenre()
Media : + getTypeOfMedia()


Abstract Amedia
Amedia : - Arraylist<listOfMedia> mediaList
Amedia : - int yearOfRelease
Amedia : - String genre
Amedia : - String typeOfMedia

Amedia : + getName()
Amedia : + getYearOfRelease()
Amedia : + getGenre()
Amedia : + getTypeOfMedia()

Amedia <|--  Movie
Movie : - String name
Movie : - int yearOfRelease
Movie : - String genre
Movie : - String typeOfMedia
Movie : - Arraylist <listOfMedia> mediaList

Movie : Movie( String name, int yearOfRelease, String genre, String typeOfMedia)
Movie : + getName()
Movie : + getYearOfRelease()
Movie : + getGenre()
Movie : + getTypeOfMedia()



Amedia <|-- Series
Series : - String name
Series : - int yearOfRelease
Series : - String genre
Series : - String typeOfMedia
Series : - int Season
Series : - int episode
Series : - Arraylist <listOfMedia> mediaList


Series : Series(String name, int yearOfRelease, String genre, int season, int episode, String typeOfMedia)
Series : + String name()
Series : + int yearOfRelease()
Series : + String genre()
Series : + String typeOfMedia()

@endum